version: '3.8'

services:
  gorev:
    image: ghcr.io/msenol/gorev:v0.9.0
    container_name: gorev-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - gorev-data:/data
    environment:
      - GOREV_ROOT=/data
      - GOREV_DATA_DIR=/data
      - GOREV_LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "gorev", "version"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    labels:
      - "com.gorev.version=0.9.0"
      - "com.gorev.description=AI-powered task management with MCP protocol"

volumes:
  gorev-data:
    name: gorev-data
    driver: local